export const tableData = [
  {
    id: 1,
    level1: '河南',
    level2: '郑州',
    level3: '金水区',
    level4: '街道',
    adress: '地址1',
    grade: '高三年级',
    name: '雷欧',
    birthday: '1992-01-01',
  },
  {
    id: 2,
    level1: '河南',
    level2: '郑州',
    level3: '郑东新区',
    level4: '街道',
    adress: '地址2',
    grade: '高三年级',
    name: '雷欧',
    birthday: '1992-01-01',
  },
  {
    id: 3,
    level1: '河南',
    level2: '郑州',
    level3: '二七区',
    level4: '街道',
    adress: '地址2',
    grade: '高三年级',
    name: '雷欧',
    birthday: '1992-01-01',
  },
  {
    id: 4,
    level1: '河南',
    level2: '周口',
    level3: '淮阳',
    level4: '街道',
    adress: '地址3',
    grade: '高三年级',
    name: '雷欧',
    birthday: '1992-01-01',
  },
  {
    id: 5,
    level1: '河南',
    level2: '周口',
    level3: '扶沟',
    level4: '街道',
    adress: '地址4',
    grade: '高三年级',
    name: '雷欧',
    birthday: '1992-01-01',
  },
  {
    id: 6,
    level1: '河南',
    level2: '周口',
    level3: '西华',
    level4: '街道',
    adress: '地址4',
    grade: '高三年级',
    name: '雷欧',
    birthday: '1992-01-01',
  },
  
];